### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by paulirish** [bramp/fix_photos_timestamp#1]
> This is a failed attempt, because Google Photos does not actually allow changing the creation timestamp from the API :( You can manually fix it via the UI. So I used this tool to ensure the new times were correct.

wow........ thank you for putting this repo up and documenting this in your readme. 

if i hadn't read this i would probably have wasted a couple hours setting up a nice pipeline only to see that key API call fail.

thanks. :)

**Comment by bramp** [comment]
I'm glad even my failed software helps :-)
